config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :flats
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flat
  belongs_to :user
end

app/models/flat.rb
class Flat < ActiveRecord::Base
  belongs_to :user
  has_many :bookings

  has_attached_file :picture,
   styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
   content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :flats
  has_many :bookings
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end

  end

  def show
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:city, :description, :availability, :picture)
  end

  def destroy
    @flat = Flat.find(params[:id])
    if @flat.user == current_user
      @flat.destroy
      redirect_to root_path, notice: 'flat was successfully deleted.'
    else
      redirect_to root_path, alert: 'you do not own this flat.'
    end
 end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate_user!

  def index
    @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/flats/_form.html.erb
<%= form_for(@flat, html: { multipart: true }) do |f| %>
 <!-- ... -->

  <% if @flat.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @flat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- [...] all the fields -->
  <div class="field">
   <%= f.label :city %><br>
   <%= f.text_field :city %>
 </div>

 <div class="field">
   <%= f.label :description %><br>
   <%= f.text_field :description %>
 </div>

 <div class="field">
   <%= f.label :availability %><br>
   <%= f.check_box :availability %>
 </div>

 <div class="field">
   <%= f.label :pictures %><br>
   <%= f.file_field :picture %>
 </div>

 <p><%= f.submit %></p>

<% end %>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/flats/show.html.erb
<div class="container">


  <div class="row">
    <div class="col-xs-4">
      <%= image_tag @flat.picture %>
    </div>
    <div class="col-xs-8">
      <h3> Flat info </h3>
      <ul>
      <li>Location: <%= @flat.city %></li>
      <li>Description: <%= @flat.description %></li>
      <li>Availability: <%= @flat.availability %></li>
      </ul>
      <button type="button" class="btn btn-danger" >Book Now</button>
     </div>
  </div>
  <%= link_to 'Back', root_path %>
</div>

app/views/home/index.html.erb
<div class="website-background">

  <div class='container'>
    <div class="row text-center">
      <div class="col-xs-12">
        <h1 class="main-title text-center">
          Welcome to JuPiBnB <i class="fa fa-binoculars"></i>
        </h1>

        <div class="text-center">
          <%= link_to 'Add flat for rent', new_flat_path, class:"btn btn-info" %>
        </div>
      </div>
    </div>

    <div class="row">

      <% @flats.each do |flat| %>
        <div class="col-xs-6">
          <div class="box">
            <div class="row">
              <div class="col-xs-8 text-center">
                <%= image_tag flat.picture.url(:medium) %>
                <p><%= flat.city %></p>
              </div>
              <div class="col-xs-4">
                <p><%= link_to 'Show', flat, class: "btn btn-primary" %></p>
                <p><%= link_to 'Delete', flat, method: :delete, data: {confirm: 'are you sure?'}, class: "btn btn-primary"  %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jupibnb</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Pacifico|Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>

  <%= render 'shared/navbar' %>


  <div class="wrapper">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </div>

  <%= render 'shared/footer' %>


</body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <p>JuPiBnB is a registered trademark ©Julie & Pia</p>
      </div>
      <div class="social col-lg-8">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
          <li><a href="#"><i class="fa fa-instagram"></i></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <%= image_tag 'logo.png', id: 'logo' %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <i class="fa fa-paper-plane"></i> Follow-us <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="https://www.facebook.com/pdiribarne?fref=ts"><i class="fa fa-facebook-square"></i> Facebook</a></li>
            <li><a href="https://twitter.com/Judepim"><i class="fa fa-twitter-square"></i> Twitter</a></li>
          </ul>
        </li>
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, root_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>